name: Travis Pflanz
favicon: null
layout_spectrum: 0.59986
typography_spectrum: 0.5516
title: "Travis's Test of The Grid"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00ccf1'
    - '#414445'
    - '#afeefa'
    - '#828585'
  brandStrength: 0.5
  lightness: 0.1397904739715159
  saturation: 0.5
  rhythmicContrast: 0.5279612487647682
purpose: []
